#config eureka
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
#config server
server:
  port: 8085
  servlet:
    context-path: /product-service
    encoding:
      charset: UTF-8
      force-response: true
#config database
spring:
  application:
    name: product-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test_erp_product?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs